name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o  # 정확하고 상세한 분석을 위해 GPT-4 사용
          PROMPT: >
            당신은 코드 리뷰를 담당하는 전문가입니다. 
            다음 코드 변경 내용을 간단하고 쉽게 설명해 주세요:
            1. 어떤 기능이 추가되었는지 또는 변경되었는지.
            2. 변경된 코드가 고객 또는 최종 사용자에게 어떤 영향을 미칠지.
            3. 코드 품질 개선 사항이 있다면 간단히 언급해 주세요.

            비개발자를 대상으로 하는 설명이므로 복잡한 기술 용어는 피하고, 고객이 이해할 수 있는 언어로 작성하세요.
          top_p: 0.5
          temperature: 0.7
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
          IGNORE_PATTERNS: /node_modules/**/*,*.md
          INCLUDE_PATTERNS: *.js,*.ts,*.py

          # Azure OpenAI를 사용하는 경우 필요한 설정
          AZURE_API_VERSION: xx
          AZURE_DEPLOYMENT: xx