name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o  # GPT-4 사용
          PROMPT: >
            You are a code review expert. Based on the code changes, briefly explain the following points:

            1. Summarize what has changed in the **frontend code** in simple terms that a non-developer can understand. For example:
               - "A new button for submitting forms has been added."
               - "The layout of the homepage has been updated to improve usability."

            2. Summarize what has changed in the **backend code** in simple terms that a non-developer can understand. For example:
               - "Payment processing now supports credit card payments."
               - "A new logging mechanism has been implemented to improve error tracking."

            3. Highlight any noticeable improvements in **code quality**, keeping explanations simple and clear. For example:
               - "Redundant code has been refactored to improve maintainability."
               - "Unnecessary files have been removed, improving system performance."

            Important:
            - Avoid technical jargon as much as possible.
            - Keep explanations concise and intuitive.

          top_p: 0.5
          temperature: 0.7
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
          IGNORE_PATTERNS: /node_modules/**/*,*.md
          INCLUDE_PATTERNS: *.js,*.ts,*.py

          # Azure OpenAI-specific settings
          AZURE_API_VERSION: xx
          AZURE_DEPLOYMENT: xx