name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4o  # GPT-4 사용
          PROMPT: >
            당신은 코드 리뷰를 담당하는 전문가입니다. 
            코드 변경 내용을 바탕으로 다음 항목을 간단히 설명하세요:
            
            1. 어떤 기능적 변화가 있었는지 비개발자가 이해할 수 있도록 설명하세요.
               - 예: "배경화면에 3D 공이 추가되었습니다." 또는 "결제 모듈이 새로 추가되어 사용자가 카드 결제를 할 수 있게 되었습니다."
            
            2. 코드 품질 개선 사항을 간단히 언급하세요.
               - 예: "반복되는 코드를 리팩터링하여 유지보수성이 향상되었습니다." 또는 "불필요한 코드를 제거하여 성능이 개선되었습니다."
            
            주의: 기술 용어는 최대한 배제하고, 간단하고 직관적인 설명을 제공하세요.
            
          top_p: 0.5
          temperature: 0.7
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
          IGNORE_PATTERNS: /node_modules/**/*,*.md
          INCLUDE_PATTERNS: *.js,*.ts,*.py

          # Azure OpenAI를 사용하는 경우 필요한 설정
          AZURE_API_VERSION: xx
          AZURE_DEPLOYMENT: xx